import { cn } from "@/lib/utils";
import { LOGOS } from "./logos/data";

interface LabLogoProps {
  logo: string;
  name: string;
  size?: "xs" | "sm" | "md" | "lg" | "xl";
  className?: string;
  tile?: boolean;
}

const SIZES = {
  xs: { box: "size-5 rounded-md", icon: "size-3" },
  sm: { box: "size-7 rounded-lg", icon: "size-4" },
  md: { box: "size-10 rounded-xl", icon: "size-5" },
  lg: { box: "size-12 rounded-xl", icon: "size-6" },
  xl: { box: "size-16 rounded-2xl", icon: "size-9" },
};

/** Inline SVG lab logo (static, trusted assets generated by scripts/build-logos.mjs). */
export function LabLogo({ logo, name, size = "md", className, tile = true }: LabLogoProps) {
  const svg = LOGOS[logo];
  const s = SIZES[size];
  const icon = svg ? (
    <span role="img" aria-label={name} className={cn("inline-block shrink-0", s.icon)} dangerouslySetInnerHTML={{ __html: svg }} />
  ) : (
    <span className={cn("font-semibold", s.icon)} aria-label={name}>
      {name.charAt(0)}
    </span>
  );
  if (!tile) return <span className={cn("inline-flex text-foreground", className)}>{icon}</span>;
  return (
    <span
      className={cn(
        "inline-flex shrink-0 items-center justify-center border bg-surface text-foreground shadow-xs dark:bg-white/[0.04]",
        s.box,
        className,
      )}
    >
      {icon}
    </span>
  );
}

export function GithubIcon({ className }: { className?: string }) {
  return <span aria-hidden="true" className={cn("inline-block shrink-0", className)} dangerouslySetInnerHTML={{ __html: LOGOS.github }} />;
}
