// Generates src/components/logos/data.ts from public/logos/*.svg.
// Root fill="currentColor" makes mono/unfilled paths follow the text color (dark/light safe).
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = "public/logos";
const entries = readdirSync(dir)
  .filter((f) => f.endsWith(".svg"))
  .sort()
  .map((file) => {
    let svg = readFileSync(join(dir, file), "utf8")
      .replace(/<title>.*?<\/title>/s, "")
      .replace(/\s(width|height|style)="[^"]*"/g, "");
    if (!/^<svg[^>]*\sfill=/.test(svg)) svg = svg.replace("<svg", '<svg fill="currentColor"');
    svg = svg.replace("<svg", '<svg width="100%" height="100%" aria-hidden="true"');
    return [file.replace(/\.svg$/, ""), svg];
  });

const body = entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n");
writeFileSync(
  "src/components/logos/data.ts",
  `// AUTO-GENERATED by scripts/build-logos.mjs — logos from @lobehub/icons (MIT).\nexport const LOGOS: Record<string, string> = {\n${body}\n};\n`,
);
console.log(`wrote ${entries.length} logos`);
